package be.ucll.jpa.exercise1.dao;

import static org.testng.Assert.assertEquals;

import java.util.List;

import javax.sql.DataSource;

import be.ucll.spring.JpaConfig;
import be.ucll.spring.MyAppConfig;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTransactionalTestNGSpringContextTests;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import be.ucll.jpa.exercise1.AddressSearchCriteria;
import be.ucll.jpa.exercise1.entities.Person;

@Test
@ContextConfiguration(classes = {JpaConfig.class, MyAppConfig.class})
@ActiveProfiles("vanilla-jdbc")
public class PersonDaoVanillaJdbcTest extends AbstractTransactionalTestNGSpringContextTests {

	@Autowired
	private DataSource dataSource;
	@Autowired
	private PersonDao personDao;

	private Person johnDoe, steveWilson;

	@BeforeMethod
	@SuppressWarnings("unused")
	private void dataSetup() {
		JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
		jdbcTemplate
				.execute("create table person2 (id bigint generated by default as identity, name varchar(255), firstname varchar(255), primary key (id))");
		jdbcTemplate
				.execute("create table person_address (id bigint generated by default as identity, person_id bigint, box varchar(255), country varchar(255), "
						+ "housenumber varchar(255), municipality varchar(255), postalcode varchar(255), street varchar(255), primary key (id), foreign key (person_id) references person2(id))");

		johnDoe = new PersonBuilder() {
			{
				firstName("John").name("Doe");
				address(new AddressBuilder() {
					{
						country("belgium");
						municipality("brussels").postalCode("1000");
						street("nieuwstraat");
						houseNumber("1").box("A");
					}
				}.build());
			}
		}.build();

		steveWilson = new PersonBuilder() {
			{
				firstName("Steve").name("Wilson");
				address(new AddressBuilder() {
					{
						country("belgium");
						municipality("antwerp").postalCode("2000");
						street("meir");
						houseNumber("10");
					}
				}.build());

				address(new AddressBuilder() {
					{
						country("spain");
						municipality("madrid").postalCode("57867");
						street("lospolloshermanos");
						houseNumber("1");
					}
				}.build());

			}
		}.build();


		personDao.savePerson(johnDoe);
		personDao.savePerson(steveWilson);
	}

	@AfterMethod(alwaysRun = true)
	@SuppressWarnings("unused")
	private void tearDown() {
		JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
		jdbcTemplate.execute("drop table person_address");
		jdbcTemplate.execute("drop table person2");
	}

	public void testAll() {
		List<Person> persons = personDao.findAll();
		assertEquals(persons.size(), 2);

		Person john = persons.stream().filter(p -> p.getFirstName().equals("John")).findFirst().get();
		Person steve = persons.stream().filter(p -> p.getFirstName().equals("Steve")).findFirst().get();

		assertEquals(john.getAddress().size(), 1);
		assertEquals(john.getName(), "Doe");

		assertEquals(steve.getAddress().size(), 2);
		assertEquals(steve.getName(), "Wilson");
	}


	public void testFindByName() {
		List<Person> persons = personDao.findByName("doe");
		assertEquals(persons.size(), 1);

		Person john = persons.stream().filter(p -> p.getFirstName().equals("John")).findFirst().get();

		assertEquals(john.getFirstName(), "John");
		assertEquals(john.getName(), "Doe");
		assertEquals(john.getAddress().size(), 1);
	}

	public void testFindByAddressCriteria() {
		AddressSearchCriteria addressSearchCriteria = new AddressSearchCriteria();
		addressSearchCriteria.setCountry("belgium");
		addressSearchCriteria.setMunicipality("antwerp");

		List<Person> persons = personDao.findByAddress(addressSearchCriteria);
		assertEquals(persons.size(), 1);
		Person steve = persons.stream().filter(p -> p.getFirstName().equals("Steve")).findFirst().get();

		assertEquals(steve.getFirstName(), "Steve");
		assertEquals(steve.getName(), "Wilson");
		assertEquals(steve.getAddress().size(), 2);

		addressSearchCriteria = new AddressSearchCriteria();
		addressSearchCriteria.setCountry("belgium");
		addressSearchCriteria.setMunicipality("brussels");

		persons = personDao.findByAddress(addressSearchCriteria);
		assertEquals(persons.size(), 1);

		Person john = persons.stream().filter(p -> p.getFirstName().equals("John")).findFirst().get();

		assertEquals(john.getFirstName(), "John");
		assertEquals(john.getName(), "Doe");
		assertEquals(john.getAddress().size(), 1);

		addressSearchCriteria = new AddressSearchCriteria();
		addressSearchCriteria.setCountry("belgium");
		persons = personDao.findByAddress(addressSearchCriteria);
		assertEquals(persons.size(), 2);
	}

	public void testDelete() {
		personDao.removePerson(personDao.findByName("Doe").iterator().next());
		personDao.removePerson(personDao.findByName("Wilson").iterator().next());
		assertEquals(personDao.findByName("Wilson").size(), 0);
		assertEquals(personDao.findByName("Doe").size(), 0);
	}
}
